 export const robots = [
    {
      id:0,
      name:'Mohan Raj',
      email:'mohanraj@gmail.com',
      username:'mohan330'
    },
    {
        id:1,
        name:'Ganeshan',
        email:'ganesh@gmail.com',
        username:'ganeshannt'
      },
      {
        id:2,
        name:'Akshay',
        email:'ak@gmail.com',
        username:'akashayrao'
      },
      {
        id:3,
        name:'Arun',
        email:'arun@gmail.com',
        username:'arunsk'
      },
      {
        id:4,
        name:'Meena',
        email:'meena@gmail.com',
        username:'meena330'
      },
      {
          id:5,
          name:'Dhanasekar',
          email:'Dhanasekar@gmail.com',
          username:'Dhanasekar'
        },
        {
          id:6,
          name:'Balaji',
          email:'balaji@gmail.com',
          username:'balaji'
        },
        {
          id:7,
          name:'Prabakaran',
          email:'Prabakaran@gmail.com',
          username:'prabakaran'
        }
]